config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :create, :destroy]
    resources :comments, only: [:destroy]
    post 'posts/:id/comments' => 'posts#create_comment', as: :create_comment
    post 'post/:id/likes' => 'posts#create_like', as: :create_like
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

    include CanCan::Ability

    def initialize(user)
    user ||= User.new
      # Define abilities for the user here. For example:
      #
      #   return unless user.present?
      #   can :read, :all
      #   return unless user.admin?
      #   can :manage, :all
      if user.is? :admin
        can :manage, :all
      else
        can :manage, Post, user_id: user.id
        can :manage, Comment, user_id: user.id
        can :read, :all
        can :add, Comment
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user, foreign_key: :user_id
  belongs_to :post, foreign_key: :post_id
  validates :text, presence: true, length: { minimum: 3, maximum: 255 }
  after_save :update_comment_counter

  def update_comment_counter
    post.comments_counter = 0 if post.comments_counter.nil?
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user, foreign_key: :user_id
  belongs_to :post, foreign_key: :post_id
  after_save :update_likes_counter

  def update_likes_counter
    post.likes_counter = 0 if post.likes_counter.nil?
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user, foreign_key: :user_id
  has_many :likes
  has_many :comments
  validates :title, presence: true, length: { minimum: 3, maximum: 255 }
  validates :text, length: { minimum: 3, maximum: 255 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  after_save :update_post_counter

  def most_recent_five_comments
    comments.order!(created_at: :desc).limit(5)
  end

  def update_post_counter
    user.posts_counter = 0 if user.posts_counter.nil?
    user.increment!(:posts_counter)
  end
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
  has_many :posts, foreign_key: :user_id
  has_many :likes
  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  Roles = [:admin, :default]

  def is?(role)
    self.role == role.to_s
  end

  def most_recent_three_posts
    posts.order(created_at: :desc).limit(3)
  end

  def authenticate(password)
    valid_password?(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?
  # layout :layout_by_resource

  private

  def layout_by_resource
    devise_controller? ? 'session' : 'application'
  end

  protected

  def after_sign_in_path_for(resource)
    if resource.is_a?(User)
      user_path(resource)
    else
      super
    end
  end

  def configure_devise_params
    devise_parameter_sanitizer.permit(:sign_up, key: %i[
                                        name
                                        email
                                        password
                                        password_confirmation
                                      ])
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @posts = Post.includes([:user]).order(user_id: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.most_recent_five_comments
  end

  def create
    @post = Post.new(post_params)
    @post.user = User.find(params[:user_id])
    if @post.save
      redirect_to user_post_path(params[:user_id], @post.id)
    else
      render :index
    end
  end

  def create_comment
    @post = Post.find(params[:id])
    Comment.create(user: User.find(params[:user_id]), post: @post, text: comment_params[:text])
    redirect_to user_post_path(params[:user_id], @post.id)
  rescue ActiveRecord::RecordInvalid
    render :show
  end

  def create_like
    @post = Post.find(params[:id])
    Like.create(user: User.find([user_id]), post: @post)
    redirect_to user_post_path(params[:user_id], @post.id)
  rescue ActiveRecord::RecordInvalid
    render :show
  end

  private

  def post_params
    params.permit(:title, :text)
  end

  def comment_params
    params.permit(:text)
  end

  def like_params
    params.permit(:post_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.most_recent_three_posts.includes([:user])
  end
end

app/controllers/usres_controller.rb
class UsersContoller < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home page</h1>

<div class-"home-card">
  <div class="home-card__body">
        <%= link_to 'Login', new_user_session_path, class: "btn btn-home" %>
        <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-home" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Playground</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks': 'reload' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_comment.html.erb
<div class="comments">
  <% comments.includes(:user).each do |comment| %>
    <div class="comments__list">
      <div class="comments__list--details">
        <p><%=user.name %>: <%= comment.text %><p>
      </div>
    </div>
  <% end %>
</div>

app/views/partials/_form.html.erb
<% if post_type == 'post' %>
  <%= form_with url: user_posts_path, method: 'post' do |f| %>
    <div class="form-group" id="form-group">
      <div class="form-group__title">
        <%= f.label :title, class: 'form-group__title--label' %>
        <%= f.text_field :title, class: 'form-group__title--title' %>
      </div>
      <div class="form-group__text">
        <%= f.label :text, class: 'form-group__text--label' %>
        <%= f.text_area :text, class: 'form-group__text--text' %>
        </div>
          <%= f.submit "Create Post", class: 'btn' %>
        </div>
      <% end %>
    <% else %>
      <div class='form-group' id='form-group'>
      <%= form_with url: user_create_comment_path, method: 'post' do |f| %>
        <div class='form-group__text'>
          <%= f.label :text, class: 'form-group_text--label' %>
          <%= f.text_area :text, class: 'form-group__text--text' %>
        </div>
        <%= f.submit 'Comment', class: 'btn' %>
      <% end %>

      <%= form_with url: user_create_like_path, method: 'post' do |f| %>
        <%= f.hidden_field :post_id, value: @post.id %>
        <%= f.submit 'Like', class: 'btn btn-like' %>
      <% end %>
    </div>
  <% end %>

app/views/partials/_post.html.erb
<div class='posts'>
  <strong>Post #<%= id %> by <%= post.user.name %></strong>
  <p><%= post.text %></p>
  <% if type == 'single_post' || type == 'all_post' %>
    <div class='posts__like-comments'>
      <p>Comments: <%=post.comments_counter %>, Likes: <%=post.likes_counter %></p>
    </div>
  <% end %>
  <% if type == 'single_post' %>
    <%= render partial: 'partials/form', locals: { post_type: '' } %>
  <% end %>
</div>

app/views/partials/_user.html.erb
<div class='users__list'>
  <div class='users__list--photo'>
    <%= image_tag user.photo, :class => 'img' if user.photo %>
  </div>
  <div class='users__list--details'>
    <h4 class='name'><%= user.name %></h4>
    <p class='posts-counter'>Number of posts: <strong><%= "#{user.posts_counter}" %></strong></p>
  </div>
</div>

app/views/posts/index.html.erb
<% user_name = '' %>
<% @posts.each.with_index(1) do |post, index| %>
  <% unless post.user.name == user_name %>
    <% user_name = post.user.name %>
    <div class="line-break"></div>
    <%= render partial: 'partials/user', locals: { user: post.user } %>
  <% end %>
  <%= render partial: 'partials/post', locals: { post: post, type: 'all_post', id: index } %>
  <%= render partial: 'partials/comment', locals: { comments: post.most_recent_five_comments, user: post.user } %>
<% end %>
<%= render partial: 'partials/form', locals: { post_type: 'post' } %>

app/views/posts/show.html.erb
<%= render partial: 'partials/post', locals: { post: @post, type: 'single_post', id: @post.id } %>
<%= render partial: 'partials/comment', locals: { comments: @comments, user: @post.user } %>

app/views/users/index.html.erb
<ul class="users">
  <% @users.each do |user| %>
    <%= link_to user_path(user) do %>
      <%= render partial: 'partials/user', locals: { user: } %>
    <% end %>
  <% end %>
</ul>

app/views/users/show.html.erb
<%= button_to 'Sign out', destroy_user_session_path, method: :delete %>

<div class="users__list">
  <%= render partial: 'partials/user', locals: { user: @user } %>
</div>

<div class="bio">
  <h4>Bio</h4>
  <p><%= @user.bio %></p>
</div>

<% @posts.each.with_index(1) do |post, index| %>
  <%= render partial: 'partials/post', locals: { post: post, type: '', id: index } %>
  <%= link_to post.title, user_post_path(@user, post) %>
<% end %>

<%= link_to 'Show all user post', user_posts_path(@user) %>